version: '3'
services:
  express:
    build: ./
    env_file:
      - .env
    ports:
      - 4000:4000
      - 4001:4001
  nginx:
    build: ./nginx
    ports:
      - 80:80 
      - 443:443
      - 8443:8443
    restart: always