apiVersion: apps/v1
kind: Deployment
metadata:
  name: chess-backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chess
  template:
    metadata:
      labels:
        app: chess
    spec:
      containers:
      - name: chess-backend
        image: ghcr.io/unizar-30226-2023-01/chess-backend:main
        ports:
        - containerPort: 4000
        - containerPort: 4001