apiVersion: apps/v1
kind: Deployment
metadata:
  name: chess-backend-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: chess
    spec:
      containers:
      - name: chess-backend
        image: localhost:5000/chess-backend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 4000