openapi: 3.1.0
info:
  version: 1.0.0
  title: Example.com
  termsOfService: 'https://example.com/tos/'
  contact:
    email: contact@example.com
    url: 'http://example.com/contact'
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  x-logo:
    url: './logo-w.png'
tags:
  - name: Auth
    description: Example echo operations.
  - name: OAuth 2.0
    description: OAuth 2.0, which stands for (open authorization), is a standard designed to allow a website or application to access resources hosted by other web applications on behalf of a user.
x-tagGroups:
  - name: Auth
    tags:
      - Auth
      - OAuth 2.0
servers:
  - url: 'http://localhost:4000/api/v1'
  - url: 'https://example.com/api/v1'
paths:
  /auth/sign-up:
    $ref: 'paths/signUp.yaml'
  /auth/sign-in:
    $ref: 'paths/signIn.yaml'
  /auth/sign-out:
    $ref: 'paths/signOut.yaml'
  /auth/sign-in/google:
    $ref: 'paths/signInGoogle.yaml'
  /auth/verify:
    $ref: paths\verify.yaml
components:
  securitySchemes:
    api_key:
      $ref: 'components/securitySchemes/api_key.yaml'
