name: Production CI

on:
  push:
    branches: [main]
  pull_request: 
    branches: [main]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  MONGO_URI: ${{ secrets.MONGO_URI }}
  REDIS_URI: ${{ secrets.REDIS_URI }}
  JWT_SECRET: ${{ secrets.JWT_SECRET }}
  GOOGLE_CALLBACK_URL: ${{ secrets.GOOGLE_CALLBACK_URL }}
  GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
  GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
  SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  install:
    name: install 📦
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v3
      with:
        cache: npm
        node-version: 16
    - name: Install Dependencies
      run: npm ci
    - name: Generate Build
      run: npm run tsc
    - name: Create Archive
      run: |
        zip -r build.zip .
    - name: Publish Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: build-artifact
        path: build.zip
        if-no-files-found: error

  # lint:
  #   name: lint 🪅
  #   needs: install
  #   runs-on: ubuntu-22.04
  #   steps:
  #   - uses: actions/checkout@v3
  #     with:
  #       fetch-depth: 0
  #   - uses: actions/setup-node@v3
  #     with:
  #       cache: npm
  #       node-version: 16
  #   - name: Install Dependencies
  #     run: npm ci
  #   - name: Lint
  #     run: npm run lint

  # test:
  #   name: test 🧪
  #   needs: [install, lint]
  #   runs-on: ubuntu-22.04
  #   steps:
  #   - uses: actions/checkout@v3
  #     with:
  #       fetch-depth: 0
  #   - uses: actions/setup-node@v3
  #     with:
  #       cache: npm
  #       node-version: 16
  #   - name: Install Dependencies
  #     run: npm ci
  #   - name: Certificates
  #     env:
  #       CERT: ${{ secrets.CERT }}
  #       KEY: ${{ secrets.KEY }}
  #     run: |
  #       mkdir -p nginx/api.gracehopper.xyz && echo "$CERT" | base64 -d > nginx/api.gracehopper.xyz/cert.pem
  #       mkdir -p nginx/api.gracehopper.xyz && echo "$KEY" | base64 -d > nginx/api.gracehopper.xyz/privkey.pem
  #   - name: Test
  #     env:
  #       NODE_ENV: test
  #       NO_AI: true
  #     run: npm run test

  deploy:
    name: deploy 🧪
    # needs: [test]
    needs: [install]
    runs-on: ubuntu-22.04
    steps:   
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Download Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: build-artifact
      - name: Extract Archive
        run: |
          unzip build.zip -d build
      - name: Create .env file
        run: |
          echo "PORT=4000" >> .env
          echo "STOCKFISH_PATH=stockfish" >> .env
          echo "SUCCESS_REDIRECT=https://reign.gracehopper.xyz" >> .env
          echo "FAILURE_REDIRECT=https://reign.gracehopper.xyz/auth/signin" >> .env
          echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> .env
          echo "REDIS_URI=${{ secrets.REDIS_URI }}" >> .env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
          echo "GOOGLE_CALLBACK_URL=${{ secrets.GOOGLE_CALLBACK_URL }}" >> .env
          echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> .env
          echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> .env
          echo "SENDGRID_API_KEY=${{ secrets.SENDGRID_API_KEY }}" >> .env
          ls -la
      - name: Build and push
        run: |
          docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest -f ./Dockerfile .
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest